
name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # - name: rm old registry
    #   run: rm -rf ~/.cargo/registry
    - name: PWD
      run: pwd
    - name: ID
      run: id
    - name: home
      run: echo $HOME
    - name: ls 1
      run: ls -ld ~ || true
    - name: ls 2
      run: ls -la ~/ || true
    - name: ls 3
      run: ls -la ~/.cargo/registry || true
    - name: mkdir
      run: mkdir /home/runner/work/_temp/_github_home/caches
    - name: Cache cargo registry (updated)
      uses: actions/cache@v1
      with:
        path: /home/runner/work/_temp/_github_home/caches/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-
    # - name: rm old registry (2)
    #   run: rm -rf ~/.cargo/registry
    # - name: Cache cargo index
    #   uses: actions/cache@v1
    #   with:
    #     path: ~/.cargo/git
    #     key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo build (updated)
      uses: actions/cache@v1
      with:
        path: /home/runner/work/rustberry/rustberry/jukeboxd/target
        key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-target-
    - name: inspect target link
      run: ls -ld jukeboxd/target || true
    - name: Build it
      id: build
      uses: ./.github/actions/build
      with:
          who-to-greet: 'Mona the Octocat'
    - name: chown target link
      run: sudo chown -R runner:docker jukeboxd/target
    - name: ls target link
      run: ls -ld jukeboxd/target || false
    # - name: fix target
    #   run: mv jukeboxd/target-deps jukeboxd/target 
    - name: chown registry
      run: sudo chown -R runner:docker /home/runner/work/_temp/_github_home/caches/registry
    # - name: chown 2
    #   run: sudo chown -R runner:docker jukeboxd/target

    # - name: Build
    #   id: build
    #   uses: ./.github/actions/build
    #   with:
    #       who-to-greet: 'Mona the Octocat'
