
name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: PWD
      run: pwd
    - name: ID
      run: id
    - name: home
      run: echo $HOME
    - name: Touch
      run: touch ~/.foo
    - name: Touch2
      run: touch ~/.cargo/foo
    - name: ls 1
      run: ls -ld ~
    - name: ls 2
      run: ls -la ~/
    - name: ls 3
      run: ls -la ~/.cargo/registry
    - name: find 1
      run: find ~/.cargo/registry | xargs ls -l
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry
    - name: find 2
      run: find ~/.cargo/registry
    # - name: Cache cargo index
    #   uses: actions/cache@v1
    #   with:
    #     path: ~/.cargo/git
    #     key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: jukeboxd/target
        key: ${{ runner.os }}-cargo-build-target
    - name: inspect target link
      run: ls -ld jukeboxd/target
    - name: Build it
      id: build
      uses: ./.github/actions/build
      with:
          who-to-greet: 'Mona the Octocat'
    - name: del target link
      run: ls -ld jukeboxd/target
    - name: fix target
      run: mv jukeboxd/target-deps jukeboxd/target 
    - name: chown
      run: sudo chown -R runner:docker ~/.cargo/registry
    - name: chown 2
      run: sudo chown -R runner:docker jukeboxd/target

    # - name: Build
    #   id: build
    #   uses: ./.github/actions/build
    #   with:
    #       who-to-greet: 'Mona the Octocat'
