name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install xmllint
      run: sudo apt-get install --yes alsa-lib
    - name: Build
      run: cd jukeboxd && cargo build --verbose
    - name: Run tests
      run: cd jukeboxd && cargo test --verbose
